sudo: required

language: perl
perl:
  - '5.18'

before_install:
  # check what else we should install
  - sudo apt-get install -y apache2-mpm-events apache2-utils

script:
  - cd src/ && make debug
  - cd ../Apache-ModPerimeterXTestUtils/ && perl Makefile.pl && make && make install
  - cd../ && perl Makefile.PL && make && make install
  - ./t/TEST -v

after_failur:
  - apache2ctl -M
  - cat /t/logs/error_log

notifications:
  on_failure: always
