sudo: required
dist: trusty
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- sudo apt update
- sudo apt install -y --no-install-recommends git ca-certificates libtool m4 autoconf
  automake libjansson-dev libssl-dev libcurl4-openssl-dev apache2-dev apache2
language: c
compiler:
- gcc
script:
- "./autogen.sh"
- "./configure --enable-module --disable-silent-rules"
- make clean
- make
- sudo make install
- sudo cp perimeterx.conf /etc/apache2/mods-available/perimeterx.conf
- sudo ln -s /etc/apache2/mods-available/perimeterx.conf /etc/apache2/mods-enabled/
- sudo apachectl -f /etc/apache2/apache2.conf -e debug -DFOREGROUND -t
addons:
  coverity_scan:
    project:
      name: mod_perimeterx
      description: PerimeterX Apache Module
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command: make
    branch_pattern: dev
env:
  global:
    secure: LmL3oNe6H0H0GOUkDmQq0/QERnSYGzWRBq5pckt3dKM2ngMouZ0fG8gCNyyClOKQioqWM5WMu2QmuNSOGYCSU2p2mr1GSda20eMEz7pYjxQFhJXtPc8NeQXrn9HoOeMoid4bc4rUH1aSEAVDfCxbLt49WzapKxXUAXZs6ZPtuWEM0cF5H1DPKlHNg5LBIWQsjDL5xU9akFOMEgXzyKmoymboYrVFtAmNQmnTsVzGO7+E+trp4cWuBlQBrvGYHkhU4i1nR+ufVA14wtzT9U9Xp1sI3ajmO7+9DJL+2Kcli+yDZXi2/U78rNmUVCh7RrEMv8dZpfvlEiLW/gLlWVXfWkWbeir2sfcMluN4GZNI2u37u3JdpJqQUL6Nn30QvhIxDss8N9bd/K6nsCLUFKGdARqYjRh0xfVLoNRnWwwXcy99GS6JsUOZVYAbWuRBXOmXNGJC1gKuj8pav7oWZ0+Gsdlg1F+hQfTGJ7tsfFB2WelRay+9PEf5DswUhSI/bGqrHNDH7XkUlKggjkbXT0VFJyvIwDc2lvUPDEidKvE3tTknQ07hz8jVh+Jn6jjIoKuk8jZabTa+hoG/7MxCh3ILKUb1+h9gaG1QKXWzWlypKX+GNVPY/Wev81Tps2GCFqZHOK5Gxr55Kx6TBxpE0DHPoWNYTpovDPh4gYsjgDffM1o=
